template_path: R53-hostedzone.yaml
stack_name: iatlas-api-hostedzone-prod
stack_tags: {{stack_group_config.stack_tags}}
parameters:
  Department: {{stack_group_config.stack_tags.Department}}
  SubDomainName: {{stack_group_config.sub_domain_name}}
  DomainName: {{stack_group_config.domain_name}}
  OwnerEmail: {{stack_group_config.stack_tags.OwnerEmail}}
  Project: {{stack_group_config.stack_tags.Project}}
