template:
  path: R53-hostedzone.yaml
stack_name: iatlas-api-hostedzone-staging
stack_tags: {{stack_group_config.stack_tags}}
parameters:
  SubDomainName: {{stack_group_config.sub_domain_name_staging}}
  DomainName: {{stack_group_config.domain_name_staging}}
